- name: Configure frontend application
  hosts: frontend
  become: yes
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: installed
      
  - name: Delete Old html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: Create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Download frontend content
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: Extract frontend content
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes
    
  - name: copy the expense.conf file
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: Enable and restart nginx service
    ansible.builtin.systemd_service:
      name: nginx
      state: restarted
      enabled: true